---
site_name: structlint Documentation
docs_dir: docs/md
site_dir: docs/site
nav:
    - About: index.md
    - CLI: cli_.md
    - Configuration: configuration_.md
    - API:
        - checks: api/checks.md
        - cli: api/cli.md
        - collection: api/collection.md
        - configuration: api/configuration.md
        - logic: api/logic.md
        - reporting: api/reporting.md
        - regexes: api/regexes.md
        - utils: api/utils.md
    - Contributing: contributing.md
plugins:
    - mkdocstrings:
        enabled: true
        default_handler: python
        handlers:
            python:
                paths:
                    - "./src"
                options:
                    show_signature_annotations: true
                    show_symbol_type_toc: true
                    show_inheritance_diagram: false
                    docstring_section_style: list
                    summary: false
                    show_root_heading: true
                    show_source: false
                    show_submodules: false
                    members: true
                    group_by_category: true
theme:
    name: material
    palette:
        scheme: slate
        accent: teal
    highlightjs: false
extra_css:
    - stylesheets/extra.css
markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        use_pygments: true
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
use_directory_urls: true
